[build]
builder = "NIXPACKS"
buildCommand = "yarn build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "yarn"]

[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["chmod +x install-webp.sh && sh install-webp.sh && yarn install --ignore-engines"]
